config_setting(
    name = "with_tbb",
    values = {
        "define": "threading=tbb"
    },
    visibility = ["//visibility:public"]
)

config_setting(
    name = "with_blas_lapack",
    define_values = {
        "with_blas": "1",
        "with_lapack": "1",
    },
    visibility = ["//visibility:public"]
)
