load(
    "//bazel:satyr_build_system.bzl",
    "satyr_cc_test"
)

satyr_cc_test(
    name = "n_array_test",
    srcs = ["n_array_test.cpp"],
    deps = ["//n_array:n_array"],
)

satyr_cc_test(
    name = "expression_test",
    srcs = ["expression_test.cpp"],
    deps = ["//n_array:n_array"],
)

satyr_cc_test(
    name = "map_test",
    srcs = ["map_test.cpp"],
    deps = ["//n_array:n_array"],
)
