load(
    "//bazel:satyr_build_system.bzl",
    "satyr_cc_test"
)

satyr_cc_test(
    name = "concept_test",
    srcs = ["concept_test.cpp"],
    deps = ["//core:core"],
)

satyr_cc_test(
    name = "for_test",
    srcs = ["for_test.cpp"],
    deps = ["//core:core"],
)

satyr_cc_test(
    name = "policy_test",
    srcs = ["policy_test.cpp"],
    deps = ["//core:core"],
)
