load(
    "//bazel:satyr_build_system.bzl",
    "satyr_cc_test"
)

satyr_cc_test(
    name = "array_test",
    srcs = ["array_test.cpp"],
    deps = ["//test:test"],
)

satyr_cc_test(
    name = "lex_test",
    srcs = ["lex_test.cpp"],
    deps = ["//test:test"],
)

satyr_cc_test(
    name = "data_dictionary_test",
    srcs = ["data_dictionary_test.cpp"],
    deps = ["//test:test"],
)

satyr_cc_test(
    name = "token_stream_test",
    srcs = ["token_stream_test.cpp"],
    deps = ["//test:test"],
)
