new_local_repository(
    name = "com_github_01org_tbb",
    path = "/usr",
    build_file = "tbb.BUILD"
)

new_local_repository(
    name = "org_netlib",
    path = "/usr",
    build_file = "netlib.BUILD"
)
