new_local_repository(
    name = "org_threadingbuildingblocks",
    path = "/usr",
    build_file = "BUILD.tbb"
)

new_local_repository(
    name = "org_netlib_blas",
    path = "/usr",
    build_file = "BUILD.blas"
)

new_local_repository(
    name = "org_netlib_lapack",
    path = "/usr",
    build_file = "BUILD.lapack"
)
